### ISSUE TITLE
Installer Won't Reload NGINX Configuration if Certbot fails

### ISSUE THREAD

**Issue by djjaam** [infiniteremote/installer#12]
This one is very simple.

Yesterday I installed Infinite Remote in a Debian 12 Server.

I wasn't ready to enable certbot to make de DCV and create the certificate for nginx, I typed c to cancel the certbot wizard and the installer didn't reload nginx to work only in HTTP.

Checking in /etc/nginx/sites-enabled and reloading nginx allowed me to access the web console.

**Comment by gitondezhuts** [comment]
no its not configured to run without SSL so please reinstall
