### ISSUE TITLE
Relay Server and Login Speed

### ISSUE THREAD

**Issue by Acwildweb** [infiniteremote/installer#15]
Hi, after several tests and attempts I empirically found the reason for the speed problem during the first connection.

- Using this configuration:
 idserver: myserver.ext
 Server relay:
Server API: **https://myserver.ext**
key: mykey

### I can Access to the addressbook but login is extremely slow about 15 seconds 

- Using this configuration:
 idserver: myserver.ext
 Server relay:
Server API: **https://myserver.ext/api**
key: mykey

### I can't Access address book but login is very fast about 1 second 

when I try to access the address book I see this error:
Unknow Error: FormatException: Unexpected Character (at line2, Character1)
<!doctype html>

I hope someone Can find the problem and solve the issue.
Thanks in advance

**Comment by gitondezhuts** [comment]
this is a know issue https://discord.com/channels/1208560123111542845/1210321863008460800/1210321863008460800
