### ISSUE TITLE
You used the style I developed!

### ISSUE THREAD

**Issue by kingmo888** [infiniteremote/installer#8]
https://github.com/kingmo888/rustdesk-api-server

**Comment by Snuupy** [comment]
https://github.com/infiniteremote/installer/commit/689d131ef82ddc4cba247470878ad9671b3942e0

I see credits/attribution were given on Feb 19, 1:44AM PST with a direct link to your project, no?

**Comment by gitondezhuts** [comment]
I told you here I had done this https://github.com/kingmo888/rustdesk-api-server/issues/36 and credit as well, I have also changed alot from what your project had as theres parts I didnt like and added gunicorn etc so its able to be used in production
